default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: postgres
  host: localhost
  port: 32773

development:
  <<: *default
  database: calendar_dev

test:
  <<: *default
  database: calendar_tes

production:
  <<: *default
  database: calendar_database

