# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c3d7a22123a0cd8b9f97c18017556f5fd9a45e75261e5bef034cb8ac52b2048ece9f737656d6f3c2dea60bee07f4c99cf4409e1e78de868fc3df893fa271f1e

test:
  secret_key_base: df39160ff975d2048e41277b2633d12122ba8ced7118f29ff1aa84e0e86a85569f22fdab100697d9a8cb508222b29b54a67170c983c667db82b73d0af7888096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
